version: 1.0.{build}

image:
- Visual Studio 2019

platform:
- x64

configuration:
- Release

init:
- set arch=
- if "%arch%"=="Win64" ( set arch= Win64)
- echo %arch%
- echo %APPVEYOR_BUILD_WORKER_IMAGE%
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019" ( set generator="Visual Studio 16 2019%arch%" )
- echo %generator%
   
install:
- cmd: choco install OpenCV -y -version 4.5.3
- cmd: choco install pandoc miktex

before_build:
- |-
    %DEPENDS% appveyor DownloadFile https://www.libsdl.org/release/SDL2-devel-2.0.16-VC.zip    
    %DEPENDS% 7z x SDL2-devel-2.0.16-VC.zip -oSDL2
    %DEPENDS% copy sdl_config\* SDL2\SDL2-2.0.16\
    set SDL2_DIR=%cd%\SDL2\SDL2-2.0.16
    set OPENCV_DIR=C:\tools\opencv\build
    %DEPENDS% appveyor DownloadFile https://github.com/microsoft/onnxruntime/releases/download/v1.9.0/onnxruntime-win-x64-1.9.0.zip
    %DEPENDS% 7z x onnxruntime-win-x64-1.9.0.zip -osrc/cpp/    
    set ONNX_MODELS_PATH=%cd%\src\models\onnx_models
        
- cmd: |-
    echo %SDL2_DIR%
    dir %SDL2_DIR%
    cd src
    cd cpp
    git submodule update --init --recursive
    move onnxruntime* onnxruntime
    set ONNXPATH=%CD%/onnxruntime
    echo %ONNXPATH%
    mkdir build
    cd build
    cmake --version
    cmake .. -G %generator% -DONNXRUNTIME_ROOTDIR=%ONNXPATH%

build:
  project: src/cpp/build/DigitsDemo.sln
  verbosity: minimal
  parallel: true    
  
after_build:
- echo %CD%
- dir %CD%
- copy %SDL2_DIR%\lib\x64\SDL2.dll Release\
- copy %OPENCV_DIR%\x64\vc15\bin\*.dll Release\
- copy %ONNX_MODELS_PATH%\*.onnx Release\
- echo %VERSION%
- 7z a DigitsDemo.zip Release\*
- cd ..\..\..\docs
- pandoc -t beamer presentation.md -V theme:Warsaw -o presentation.pdf

artifacts:
- path: src/cpp/build/DigitsDemo.zip
  
deploy:
  - provider: GitHub
    auth_token:
      secure: zpjN8eGGNYIYn5YgqTdjTyG/yE8JuAnSh+KgWRuQCL4jIu4T85dYjDsS52m8VnGG
    release: DigitsDemo-v$(APPVEYOR_BUILD_VERSION)
    artifact: src/cpp/build/DigitsDemo.zip           # upload all NuGet packages to release assets
    draft: false
    prerelease: false
    on:
      branch: main                # release from master branch only
      APPVEYOR_REPO_TAG: false       # deploy on tag push only
